version: '2'

services:
  libqmkl: &libqmkl-env
    image: idein/cross-librpigrafx2:latest
    volumes:
      - /home/idein/cross/usr/armv6-rpi-linux-gnueabihf

  qmkl-sys: &build-env
    image: idein/cross-rpi-rust:latest
    environment:
      LIBCLANG_INCLUDE_PATH: '/usr/include/clang/3.9.1/include'
      PKG_CONFIG_PATH: '/opt/vc/lib/pkgconfig:/home/idein/cross/usr/armv6-rpi-linux-gnueabihf/lib/pkgconfig'
    volumes:
      - .:/work
      - cargo-cache:/home/idein/.cargo
    volumes_from:
      - libqmkl
    working_dir: /work

  build-qmkl-sys:
    << : *build-env
    command: |
      bash -c "
        sudo dpkg --add-architecture armhf
        sudo apt-get update -y && sudo apt-get install -y libc6-dev:armhf
        cargo build --target=arm-unknown-linux-gnueabihf
      "

volumes:
  cargo-cache:

